# This workflow will build a golang calculator project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI/CD

on:
  push:
    paths:
      - "calculator/calculator.go"
  pull_request:
    paths:
      - "calculator/calculator.go"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    # - name: Deploy
    #   if: github.ref == 'refs/heads/main' && success()  # Only deploy on successful builds on the main branch
    #   run: echo "Deploying your application..."  # Replace this with your actual deployment script


